  obs filters:
  - filter: PreQC
    maxvalue: 0
  - filter: GOMsaver
    filename: {{OutDBDir}}/{{geoPrefix}}_amsua_n15.nc4
  - filter: YDIAGsaver
    filename: {{OutDBDir}}/{{diagPrefix}}_amsua_n15.nc4 
