  obs filters:
  - filter: Domain Check
    where:
    - variable:
        name: MetaData/height
      minvalue: 0.0
      maxvalue: 30000.0
    - variable:
        name: MetaData/earthRadiusCurvature
      minvalue: 6250000.0
      maxvalue: 6450000.0
    - variable:
        name: MetaData/geoidUndulation
      minvalue: -200.0
      maxvalue: 200.0
  - filter: GOMsaver
    filename: {{OutDBDir}}/{{geoPrefix}}_gnssrorefncep.nc4
  - filter: YDIAGsaver
    filename: {{OutDBDir}}/{{diagPrefix}}_gnssrorefncep.nc4
  - filter: ROobserror
    variable: refractivity
    errmodel: NCEP
    <<: *multiIterationFilter
